#/*******************************************************************************
#
# WARNING This file is subject to the terms and conditions defined in the file
# 'LICENSE.txt', which is part of this source code package. Please ensure you
# have read the 'LICENSE.txt' file before using this software.
#
#********************************************************************************/

# xinitrc file for testing the window manager

# start some programs
xclock &
xeyes &
# sleep 2 && mate-panel &
sleep 2 && xterm &

# start the window manager
exec ./bin/debug/x86-64-GCC-Linux/pharaoh
